name: "Multi Event Pipeline / Workflow"

on:
    push:
        branches:
            - test
            - master
    
    pull_request: 
        branches:
            - master

jobs:
    on-Push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on Push from test"
              run: echo "Push from Test"

    on-Pull_Request: 
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on Pull Request"
              run: echo "Pull Request from Test"